version: "3.8"

services:
  frontend:
    build: ./startup_bridge
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./Back-end
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
